name: Allure Playwright Pytest BDD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          npx playwright install

      - name: Run tests
        run: |
          pytest --alluredir=allure-results

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report