name: Run tests and publish report

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      ## Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      ## Run tests
      - name: Run tests
        run: pytest

      ## Allure report
      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline
          allure generate allure-results -o allure-report --clean

      - name: Make directory history
        run: mkdir -p allure-results/history

      - name: Copy history
        run: |
          if [ -d "./.github/allure-report/last-history" ]; then
            cp -R ./.github/allure-report/last-history/* allure-results/history/
          fi

      ## Deploy step
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: allure-report
          keep_files: false