name: Beni's tryout
description: 'Publish Allure report with history to GitHub Pages'

on:
  workflow_dispatch: # Trigger the workflow manually
    inputs:
      tags: # Input parameter for test scenario tags
        description: "PyTest scenario bdd tags"
        required: true
        default: "smoke"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Allure history
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: ${{ github.event.inputs.gh-pages-branch }}
          path: allure-report

      - name: Allure Report Generation
        uses: telia-actions/simple-elf-allure-report@v1
        with:
          allure_results: ${{ github.event.inputs.allure-results }}
          allure_history: allure-history
          keep_reports: ${{ github.event.inputs.keep-reports }}
          subfolder: ${{ github.event.inputs.subfolder }}
          test_env_name: ${{ github.event.inputs.test-env-name }}

      - name: Deploy report to Github Pages
        uses: telia-actions/peaceiris-gh-pages@v4
        with:
          github_token: ${{ github.event.inputs.gh-token }}
          publish_branch: ${{ github.event.inputs.gh-pages-branch }}
          publish_dir: ./allure-history

      - id: report-link
        run: |
          if [[ '${{ github.event.inputs.subfolder }}' != '' ]]; then export URL_SUBFOLDER=${{ github.event.inputs.subfolder }}/; fi
          echo "report-url=$(gh api repos/$GITHUB_REPOSITORY/pages | jq .html_url | sed -e 's/^"//' -e 's/"$//')${URL_SUBFOLDER}${{ github.run_number }}/" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.event.inputs.gh-token }}
        shell: bash

    outputs:
      report-url:
        description: "URL for Allure report"
        value: ${{ steps.report-link.outputs.report-url }}