name: Playwright BDD Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Test Suite to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - service
          - api

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-bdd pytest-playwright allure-pytest

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Run all tests
        if: ${{ github.event.inputs.test_suite == 'all' || github.event.inputs.test_suite == '' }}
        run: |
          # pytest tests/features --alluredir=allure-results
           pytest
        continue-on-error: true

      - name: Run service tests
        if: ${{ github.event.inputs.test_suite == 'service' }}
        run: |
          pytest tests/features -m service --alluredir=allure-results
        continue-on-error: true

      - name: Run API tests
        if: ${{ github.event.inputs.test_suite == 'api' }}
        run: |
          pytest tests/features -m api --alluredir=allure-results
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history