name: otmans fix

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set-up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clean previous test results
        run: rm -rf allure-results

      - name: Run tests
        run: pytest

      - name: Copy historical data
        run: |
          if [ -d "allure-report/history" ]; then
            cp -R allure-report/history/* allure-results/history/
          fi

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline
          allure generate allure-results -o allure-report --clean

      - name: Preserve history for next run
        run: |
          mkdir -p allure-report/history
          cp -R allure-results/history/* allure-report/history/

      - name: Deploy Allure Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: allure-report
          keep_files: true